### ISSUE TITLE
tools for converting breakdancer output into iAnnotateSV

### ISSUE THREAD

**Issue by anyone1985** [rhshah/iAnnotateSV#15]
Is there any tools to convert the output of breakdancer into iAnnotateSV? The 3,6 columns of breakdancer are strings that record the number of reads mapped to the plus (+) or the minus (-) strand in the anchoring regions. How should I determine the orientation?

**Comment by rhshah** [comment]
- Nope, currently we do not have conversion script that works for BreakDancer. 
- We do have on that will work with Delly version 0.7.5. You can find that here in [iCallSV](https://github.com/rhshah/iCallSV/blob/master/iCallSV/dellyVcf2Tab.py)
- From what I see is the breakdancer output is the same number of reads on both breakpoints would determine the orientation. If this is the output of breakdance:
`
Example 1:
1 10000 10+0- 2 20000 7+10- CTX -296 99 10 tB|10 1.00 BreakDancerMax-0.0.1 t1
`
Then for breakpoint 1 it would be (+) which you can convert to 0 for iAnnotateSV and for breakpoint 2 it would be (-) which you can convert to 1 for iAnnotateSV

Hope that helps. 
If this works, I will be happy to add that as utilities for conversion if you would like to do a PR for it.
