### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'Int64Index'

### ISSUE THREAD

**Issue by haoziyeung** [rhshah/iAnnotateSV#21]
Hello,there,i have a ERROR message,but i don't know how to fix it 

when i run this:
/gpfs/users/yanghao/software/anaconda2/bin/python /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/iAnnotateSV.py -r hg19 -i /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina_B1701-sm/Illumina_B1701-sm_allSVFiltered.tab -o /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina_B1701-sm -ofp Illumina_B1701-sm_allSVFiltered -d 3000 -c /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/data/canonicalInfo/cannonical_transcripts.txt -rr /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/data/repeat_region/hg19_repeatRegion.tsv -cc /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/data/cosmic/CosmicConsensus_transFeb2014.tsv -dgv /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/data/database_of_genomic_variants/hg19_DGv_Annotation.tsv -v -p -u /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/data/UcscUniprotdomainInfo/hg19.uniprot.spAnnot.table.txt

raise an ERROR:
Traceback (most recent call last):
  File "/gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/iAnnotateSV.py", line 312, in <module>
    main()
  File "/gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/iAnnotateSV.py", line 203, in main
    plotSV(plotDF, NewRefDF, uniprotPath, args)
  File "/gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/iAnnotateSV.py", line 304, in plotSV
    vsv.VisualizeSV(svDF, refDF, upDF, args)
  File "/gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/VisualizeSV.py", line 47, in VisualizeSV
    (domain1Idx, maxLen1, minLen1) = processData(chr1, transcript1, refDF, upDF)
  File "/gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/VisualizeSV.py", line 215, in processData
    transcriptIdx = int(refDF[refDF['#name'] == transcript].index)
TypeError: int() argument must be a string or a number, not 'Int64Index'

can anybody help me ?thanks alot!!
![qq 20180117211802](https://user-images.githubusercontent.com/16606564/35044581-f45e8800-fbcb-11e7-87a5-10b68783fb4e.png)

**Comment by haoziyeung** [comment]
When i remove some args,it sucess,

/gpfs/users/yanghao/software/anaconda2/bin/python /gpfs/users/yanghao/software/iAnnotateSV-1.0.5/iAnnotateSV/iAnnotateSV.py -r hg19 -i Illumina_B1701-sm_allSVFiltered.tab -o . -r hg19 -d 3000 -ofp Illumina_B1701-sm_allSVFiltered

**Comment by rhshah** [comment]
My apologies the part of visualization has issues in some cases. Please avoid using `-p`. If you downloaded the repo using git-lfs you should get proper files and you wont need to provide all the arguments. Also I will add `-c` as a requirement in future release as in some cases without `-c` you might get errors as there is no best transcript available.

**Comment by haoziyeung** [comment]
@rhshah ,thanks very much :)
