### ISSUE TITLE
Incorrect Breakpoint Annotation for UTR

### ISSUE THREAD

**Issue by rhshah** [rhshah/iAnnotateSV#8]
Re: {cvr}/sample/22203
THe site2 description for NSUN4 is incorrect. The breakpoint occurs after the 3UTR of the gene in the positive strand. However, the description sites the Promoter region. Though the "26Kb from tx start" is correct.

**Comment by andurill** [comment]
just another example {cvr}/sample/23114 for reference

The TP53 SV breakpoint should be after 3UTR (TP53 on the - strand), not promoter.

**Comment by rhshah** [comment]
@andurill fixed this issue in the development branch
